# Generated by Django 3.2.6 on 2022-04-13 06:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_lifecycle.mixins
import ingredients.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_status', models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('INACTIVE', 'INACTIVE')], default='ACTIVE', max_length=200, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('document_code', models.CharField(blank=True, max_length=400, null=True)),
                ('ingredient_name', models.CharField(blank=True, max_length=400, null=True)),
                ('stock_count', models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True)),
                ('image_path', models.ImageField(blank=True, null=True, upload_to=ingredients.models.upload_ingredient_image)),
                ('type', models.CharField(choices=[('SOLID', 'SOLID'), ('GRANULAR', 'GRANULAR'), ('LIQUID', 'LIQUID')], default=None, max_length=200, null=True)),
                ('unit', models.CharField(choices=[('GRAM', 'GRAM'), ('KILOGRAM', 'KILOGRAM'), ('TABLE_SPOON', 'TABLE_SPOON'), ('MILLILITER', 'MILLILITER')], default=None, max_length=200, null=True)),
                ('invoked_count', models.IntegerField(blank=True, default=0, null=True)),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ingredient_creator', to=settings.AUTH_USER_MODEL)),
                ('editor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ingredient_editor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Coordinates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_status', models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('INACTIVE', 'INACTIVE')], default='ACTIVE', max_length=200, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('document_code', models.CharField(blank=True, max_length=400, null=True)),
                ('type', models.CharField(choices=[('INGREDIENT', 'INGREDIENT'), ('DUMPER', 'DUMPER'), ('PICKER', 'PICKER'), ('PLATE', 'PLATE')], default=None, max_length=200, null=True)),
                ('name', models.CharField(default=None, max_length=200)),
                ('coordinate_x', models.IntegerField(blank=True, default=0, null=True)),
                ('coordinate_y', models.IntegerField(blank=True, default=0, null=True)),
                ('ordinal', models.IntegerField(default=0)),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coordinates_creator', to=settings.AUTH_USER_MODEL)),
                ('editor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coordinates_editor', to=settings.AUTH_USER_MODEL)),
                ('ingredient', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ingredient_map', to='ingredients.ingredient')),
                ('primary', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='ingredients.coordinates')),
            ],
            options={
                'abstract': False,
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
    ]
