# Generated by Django 3.2.6 on 2022-04-16 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0002_alter_recipe_queue_handler'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='step',
            name='step_description',
        ),
    ]
