# Generated by Django 3.2.6 on 2022-04-16 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0003_remove_step_step_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='step',
            name='step_type',
            field=models.CharField(choices=[('Pickup Type', 'Pickup Type'), ('Wok Type', 'Wok Type')], default=None, max_length=200, null=True),
        ),
    ]
