# Generated by Django 3.2.6 on 2022-04-20 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0005_rename_queue_handler_recipe_handler_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='handler_type',
            field=models.CharField(choices=[('STIR_FRY_MODULE', 'STIR_FRY_MODULE'), ('DEEP_FRY_MODULE', 'DEEP_FRY_MODULE'), ('GRILLING_MODULE', 'GRILLING_MODULE'), ('DRINKS_MODULE', 'DRINKS_MODULE'), ('BOILER_MODULE', 'BOILER_MODULE'), ('STEAMING_MODULE', 'STEAMING_MODULE'), ('TRANSPORTER_MODULE', 'TRANSPORTER_MODULE')], default=None, max_length=200, null=True),
        ),
    ]
