# Generated by Django 3.2.6 on 2022-04-21 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0008_alter_substep_step'),
    ]

    operations = [
        migrations.AddField(
            model_name='substep',
            name='parameters',
            field=models.CharField(default='', max_length=3000),
        ),
    ]
