# Generated by Django 3.2.6 on 2022-04-13 06:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_lifecycle.mixins


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_status', models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('INACTIVE', 'INACTIVE')], default='ACTIVE', max_length=200, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('document_code', models.CharField(blank=True, max_length=400, null=True)),
                ('name', models.CharField(blank=True, max_length=400, null=True)),
                ('instance_code', models.CharField(blank=True, max_length=400, null=True)),
                ('queue_handler', models.CharField(choices=[('cooking_module', 'cooking_module'), ('pickup_module', 'pickup_module')], default=None, max_length=200, null=True)),
                ('ip_address', models.CharField(blank=True, max_length=400, null=True, unique=True)),
                ('wok_camera', models.CharField(blank=True, max_length=400, null=True)),
                ('camera_opened', models.BooleanField(default=False, null=True)),
                ('port', models.IntegerField(default=8888)),
                ('status', models.CharField(choices=[('BUSY', 'BUSY'), ('AVAILABLE', 'AVAILABLE'), ('DISABLED', 'DISABLED')], default='AVAILABLE', max_length=200, null=True)),
                ('connectivity', models.CharField(choices=[('CONNECTED', 'CONNECTED'), ('DISCONNECTED', 'DISCONNECTED')], default='DISCONNECTED', max_length=200, null=True)),
                ('type', models.CharField(choices=[('STIR_FRY_MODULE', 'STIR_FRY_MODULE'), ('DEEP_FRY_MODULE', 'DEEP_FRY_MODULE'), ('GRILLING_MODULE', 'GRILLING_MODULE'), ('DRINKS_MODULE', 'DRINKS_MODULE'), ('BOILER_MODULE', 'BOILER_MODULE'), ('STEAMING_MODULE', 'STEAMING_MODULE'), ('TRANSPORTER_MODULE', 'TRANSPORTER_MODULE')], default='STIR_FRY_MODULE', max_length=200, null=True)),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='module_creator', to=settings.AUTH_USER_MODEL)),
                ('editor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='module_editor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
    ]
