# Generated by Django 3.2.6 on 2022-04-14 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='queue_handler',
            field=models.CharField(choices=[('stir_fry', 'stir_fry'), ('deep_fry', 'deep_fry'), ('boiler', 'boiler'), ('pickup_module', 'pickup_module')], default=None, max_length=200, null=True),
        ),
    ]
