# Generated by Django 3.2.6 on 2022-04-16 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0002_alter_module_queue_handler'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='connectivity',
            field=models.CharField(blank=True, choices=[('CONNECTED', 'CONNECTED'), ('DISCONNECTED', 'DISCONNECTED')], default='DISCONNECTED', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='module',
            name='port',
            field=models.IntegerField(blank=True, default=8888, null=True),
        ),
        migrations.AlterField(
            model_name='module',
            name='status',
            field=models.CharField(blank=True, choices=[('BUSY', 'BUSY'), ('AVAILABLE', 'AVAILABLE'), ('DISABLED', 'DISABLED')], default='AVAILABLE', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='module',
            name='type',
            field=models.CharField(blank=True, choices=[('STIR_FRY_MODULE', 'STIR_FRY_MODULE'), ('DEEP_FRY_MODULE', 'DEEP_FRY_MODULE'), ('GRILLING_MODULE', 'GRILLING_MODULE'), ('DRINKS_MODULE', 'DRINKS_MODULE'), ('BOILER_MODULE', 'BOILER_MODULE'), ('STEAMING_MODULE', 'STEAMING_MODULE'), ('TRANSPORTER_MODULE', 'TRANSPORTER_MODULE')], default='STIR_FRY_MODULE', max_length=200, null=True),
        ),
    ]
