# Generated by Django 3.2.6 on 2022-04-20 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0003_auto_20220416_0253'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='type',
        ),
    ]
