# Generated by Django 3.2.6 on 2022-04-20 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0005_auto_20220420_0339'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='ip_address',
        ),
    ]
