# Generated by Django 3.2.6 on 2022-04-20 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0006_remove_module_ip_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='module',
            old_name='queue_handler',
            new_name='ip_address',
        ),
    ]
