# Generated by Django 3.2.6 on 2022-04-22 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0008_modulecontroller'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modulecontroller',
            old_name='ip_address',
            new_name='controller_type',
        ),
    ]
