# Generated by Django 3.2.6 on 2022-04-18 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskset',
            name='task_name',
            field=models.CharField(max_length=400, null=True),
        ),
    ]
