# Generated by Django 3.2.6 on 2022-04-20 03:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0003_auto_20220416_0253'),
        ('tasks', '0002_alter_taskset_task_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskset',
            name='handler_type',
            field=models.CharField(choices=[('stir_fry', 'stir_fry'), ('deep_fry', 'deep_fry'), ('boiler', 'boiler'), ('pickup_module', 'pickup_module')], default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='taskset',
            name='module_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='module.module'),
        ),
    ]
