# Generated by Django 3.2.6 on 2022-04-20 03:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0003_auto_20220416_0253'),
        ('tasks', '0003_auto_20220420_0306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskset',
            name='module_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='module.module'),
        ),
    ]
