# Generated by Django 3.2.6 on 2022-04-22 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_taskset_task_origin'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskset',
            name='total_steps',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
