# Generated by Django 3.2.6 on 2022-04-22 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_taskset_total_steps'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskset',
            name='current_step',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
