# Generated by Django 3.2.6 on 2022-04-22 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_auto_20220422_0301'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskset',
            name='processing_time',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='taskset',
            name='waiting_time',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
