# Generated by Django 3.2.6 on 2022-04-22 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0011_auto_20220422_0329'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskset',
            name='processing_time',
        ),
        migrations.RemoveField(
            model_name='taskset',
            name='waiting_time',
        ),
    ]
