# Generated by Django 3.2.6 on 2022-04-22 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0013_auto_20220422_0359'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskset',
            name='origin_index',
        ),
        migrations.AddField(
            model_name='taskset',
            name='task_origin',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('RECEIVED', 'RECEIVED'), ('STARTED', 'STARTED'), ('SUCCESS', 'SUCCESS'), ('FAILURE', 'FAILURE'), ('REVOKED', 'REVOKED'), ('REJECTED', 'REJECTED'), ('RETRY', 'RETRY'), ('IGNORED', 'IGNORED')], default='PENDING', max_length=200, null=True),
        ),
    ]
